version: '3.8'
services:
  server:
    container_name: server
    image: golang:1-alpine
    build: .
    command: go run main.go
    expose:
      - '9090'
    ports:
      - '9090:9090'
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - '5432'
    ports:
      - '5432:${POSTGRES_PORT}'
    volumes:
      - ./database/postgres/postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./database/postgres/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
